<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\BuildPath.props" />
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Bunject.NewYardSystem</RootNamespace>
    <AssemblyName>Bunject.NewYardSystem</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
    <GenerateBindingRedirectsOutputType>false</GenerateBindingRedirectsOutputType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Data.DataSetExtensions">
      <Private>False</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(PaquerettePath)\Paquerette Down the Bunburrows_Data\Managed\Assembly-CSharp.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.TextMeshPro">
      <HintPath>$(PaquerettePath)\Paquerette Down the Bunburrows_Data\Managed\Unity.TextMeshPro.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(PaquerettePath)\Paquerette Down the Bunburrows_Data\Managed\Newtonsoft.Json.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bunject\Bunject.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Assets\BNYS\ExtendedRegion.png" />
    <Content Include="Assets\BNYS\UserGuide.txt" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" Version="1.*" PrivateAssets="all" />
    <PackageReference Include="BepInEx.Core" Version="5.*">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="UnityEngine.Modules" Version="6000.3.4">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  <!-- Generate properties that will let "Running" launch the game based on BuildPath.props -->
  <Target Name="GenerateGameLaunchSettings" BeforeTargets="BeforeBuild;Rebuild">
    <PropertyGroup>
      <_GameExeJson>$([System.String]::Copy('$(PaquerettePath)\Paquerette Down the Bunburrows.exe').Replace('\', '\\'))</_GameExeJson>
      <_GameDirJson>$([System.String]::Copy('$(PaquerettePath)').Replace('\', '\\'))</_GameDirJson>
      <_LaunchSettingsJson>{ "profiles": { "Paquerette (Game)": { "commandName": "Executable", "executablePath": "$(_GameExeJson)", "workingDirectory": "$(_GameDirJson)" } } }</_LaunchSettingsJson>
    </PropertyGroup>
    <WriteLinesToFile File="$(MSBuildProjectDirectory)\Properties\launchSettings.json" Lines="$(_LaunchSettingsJson)" Overwrite="true" WriteOnlyWhenDifferent="true" />
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(MSBuildProjectDirectory)\Assets\BNYS&quot; &quot;$(PaquerettePluginPath)\BNYS&quot; /E /C /I /Y&#xD;&#xA;xcopy &quot;$(TargetDir)*.dll&quot; &quot;$(PaquerettePluginPath)&quot; /y /f&#xD;&#xA;xcopy &quot;$(TargetDir)Bunject.NewYardSystem.dll&quot; &quot;Deploy\*&quot; /y /f" />
  </Target>
  <Target Name="ZipBuild" AfterTargets="PostBuild" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <ZipDirectory SourceDirectory="Assets\BNYS\Pursuit" DestinationFile="Deploy\Pursuit.bnys" Overwrite="true" />
    <ZipDirectory SourceDirectory="Deploy" DestinationFile="..\Deploy\BNYS.zip" Overwrite="true" />
  </Target>
</Project>